# Generated by Django 4.1.4 on 2023-02-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospitalV', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='heces',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
